import type { ExerciseLibraryItem, WorkoutTemplateExercise } from '../types'

export const EXERCISE_LIBRARY: ExerciseLibraryItem[] = [
  // ===== 胸 =====
  { id: 'exe-bench-press', name: '杠铃平板卧推', muscleGroup: '胸', movementPattern: 'chest', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-incline-bench', name: '杠铃上斜卧推', muscleGroup: '上胸', movementPattern: 'chest', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-decline-bench', name: '杠铃下斜卧推', muscleGroup: '下胸', movementPattern: 'chest', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-db-bench', name: '哑铃平板卧推', muscleGroup: '胸', movementPattern: 'chest', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-db-incline', name: '上斜哑铃卧推', muscleGroup: '上胸', movementPattern: 'chest', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-cable-fly', name: '绳索夹胸', muscleGroup: '胸中缝', movementPattern: 'chest', equipment: 'cable', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-pec-deck', name: '蝴蝶机夹胸', muscleGroup: '胸中缝', movementPattern: 'chest', equipment: 'machine', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-pushup', name: '俯卧撑', muscleGroup: '胸', movementPattern: 'chest', equipment: 'bodyweight', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-dips', name: '双杠臂屈伸', muscleGroup: '下胸', movementPattern: 'chest', equipment: 'bodyweight', isCustom: false, createdAt: '', updatedAt: '' },
  // ===== 肩 =====
  { id: 'exe-ohp', name: '杠铃推举', muscleGroup: '肩整体', movementPattern: 'shoulders', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-db-ohp', name: '坐姿哑铃推肩', muscleGroup: '肩整体', movementPattern: 'shoulders', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-lateral-raise', name: '哑铃侧平举', muscleGroup: '肩中束', movementPattern: 'shoulders', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-cable-lateral', name: '绳索侧平举', muscleGroup: '肩中束', movementPattern: 'shoulders', equipment: 'cable', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-front-raise', name: '前平举', muscleGroup: '肩前束', movementPattern: 'shoulders', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-rear-delt-fly', name: '反向飞鸟', muscleGroup: '肩后束', movementPattern: 'shoulders', equipment: 'machine', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-face-pull', name: '面拉', muscleGroup: '肩后束、肩袖', movementPattern: 'shoulders', equipment: 'cable', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-upright-row', name: '直立划船', muscleGroup: '肩', movementPattern: 'shoulders', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-db-shrug', name: '哑铃耸肩', muscleGroup: '斜方肌', movementPattern: 'shoulders', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  // ===== 背 =====
  { id: 'exe-pulldown', name: '高位下拉', muscleGroup: '背阔整体', movementPattern: 'back', equipment: 'machine', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-pullup', name: '引体向上', muscleGroup: '背阔整体', movementPattern: 'back', equipment: 'bodyweight', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-bent-row', name: '杠铃俯身划船', muscleGroup: '厚背', movementPattern: 'back', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-db-row', name: '单臂哑铃划船', muscleGroup: '背', movementPattern: 'back', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-seated-cable-row', name: '坐姿绳索划船', muscleGroup: '中下背', movementPattern: 'back', equipment: 'cable', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-straight-arm-pulldown', name: '直臂绳索下压', muscleGroup: '背阔下沿', movementPattern: 'back', equipment: 'cable', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-t-bar-row', name: 'T杠划船', muscleGroup: '背', movementPattern: 'back', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-chest-supported-row', name: '器械划船', muscleGroup: '背', movementPattern: 'back', equipment: 'machine', isCustom: false, createdAt: '', updatedAt: '' },
  // ===== 二头 =====
  { id: 'exe-bb-curl', name: '杠铃弯举', muscleGroup: '二头', movementPattern: 'arms', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-db-curl', name: '哑铃弯举', muscleGroup: '二头', movementPattern: 'arms', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-alt-db-curl', name: '哑铃交替弯举', muscleGroup: '二头峰值', movementPattern: 'arms', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-hammer-curl', name: '锤式弯举', muscleGroup: '二头', movementPattern: 'arms', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-cable-curl', name: '绳索弯举', muscleGroup: '二头', movementPattern: 'arms', equipment: 'cable', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-prey-curl', name: '托臂弯举', muscleGroup: '二头', movementPattern: 'arms', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  // ===== 三头 =====
  { id: 'exe-cable-pushdown', name: '绳索下压', muscleGroup: '肱三头肌', movementPattern: 'arms', equipment: 'cable', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-overhead-ext', name: '颈后臂屈伸', muscleGroup: '肱三头肌', movementPattern: 'arms', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-skull-crusher', name: '仰卧臂屈伸', muscleGroup: '肱三头肌', movementPattern: 'arms', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-close-grip-bench', name: '窄距卧推', muscleGroup: '肱三头肌', movementPattern: 'push', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  // ===== 腿 =====
  { id: 'exe-squat', name: '杠铃深蹲', muscleGroup: '股四头肌、臀', movementPattern: 'legs', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-front-squat', name: '前蹲', muscleGroup: '股四头肌', movementPattern: 'legs', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-leg-press', name: '腿举', muscleGroup: '下肢大容量', movementPattern: 'legs', equipment: 'machine', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-leg-ext', name: '坐姿腿屈伸', muscleGroup: '股四头肌', movementPattern: 'legs', equipment: 'machine', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-leg-curl', name: '俯卧腿弯举', muscleGroup: '腘绳肌', movementPattern: 'legs', equipment: 'machine', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-romanian-deadlift', name: '罗马尼亚硬拉', muscleGroup: '腘绳肌、臀', movementPattern: 'legs', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-deadlift', name: '传统硬拉', muscleGroup: '全身后链', movementPattern: 'legs', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-lunge', name: '箭步蹲', muscleGroup: '腿', movementPattern: 'legs', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-smith-lunge', name: '史密斯机箭步蹲', muscleGroup: '腿', movementPattern: 'legs', equipment: 'smith_machine', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-goblet-squat', name: '高脚杯深蹲', muscleGroup: '股四头肌', movementPattern: 'legs', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-bulgarian-split', name: '保加利亚分腿蹲', muscleGroup: '腿', movementPattern: 'legs', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-hip-thrust', name: '臀推', muscleGroup: '臀', movementPattern: 'glutes_hams', equipment: 'barbell', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-hyperextension', name: '山羊挺身', muscleGroup: '下背、腘绳肌', movementPattern: 'glutes_hams', equipment: 'bodyweight', isCustom: false, createdAt: '', updatedAt: '' },
  // ===== 小腿 =====
  { id: 'exe-standing-calf', name: '站姿提踵', muscleGroup: '小腿', movementPattern: 'calves', equipment: 'machine', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-seated-calf', name: '坐姿提踵', muscleGroup: '小腿', movementPattern: 'calves', equipment: 'machine', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-db-calf', name: '哑铃提踵', muscleGroup: '小腿', movementPattern: 'calves', equipment: 'dumbbell', isCustom: false, createdAt: '', updatedAt: '' },
  // ===== 核心 =====
  { id: 'exe-plank', name: '平板支撑', muscleGroup: '核心', movementPattern: 'core', equipment: 'bodyweight', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-hanging-leg-raise', name: '悬垂举腿', muscleGroup: '腹肌', movementPattern: 'core', equipment: 'bodyweight', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-cable-crunch', name: '绳索卷腹', muscleGroup: '腹肌', movementPattern: 'core', equipment: 'cable', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-russian-twist', name: '俄罗斯转体', muscleGroup: '腹斜肌', movementPattern: 'core', equipment: 'bodyweight', isCustom: false, createdAt: '', updatedAt: '' },
  { id: 'exe-ab-wheel', name: '腹肌滚轮', muscleGroup: '核心', movementPattern: 'core', equipment: 'bodyweight', isCustom: false, createdAt: '', updatedAt: '' },
]

// Build the bridge: workout_template → exercise_library
export const WORKOUT_TEMPLATE_EXERCISES: WorkoutTemplateExercise[] = [
  // ===== 推日A =====
  { id: 'wte-push-1', workoutTemplateId: 'push-a', exerciseId: 'exe-bench-press', displayName: '杠铃平板卧推', orderIndex: 1,
    targetSets: 4, minReps: 8, maxReps: 12, restSecondsMin: 90, restSecondsMax: 120, warmupSets: 2, warmupPercent: 50, isEachSide: false },
  { id: 'wte-push-2', workoutTemplateId: 'push-a', exerciseId: 'exe-db-incline', displayName: '上斜哑铃卧推', orderIndex: 2,
    targetSets: 3, minReps: 8, maxReps: 12, restSecondsMin: 60, restSecondsMax: 90, warmupSets: 1, warmupPercent: 50, isEachSide: false },
  { id: 'wte-push-3', workoutTemplateId: 'push-a', exerciseId: 'exe-db-ohp', displayName: '坐姿哑铃推肩', orderIndex: 3,
    targetSets: 4, minReps: 8, maxReps: 12, restSecondsMin: 90, restSecondsMax: 90, warmupSets: 1, warmupPercent: 50, isEachSide: false },
  { id: 'wte-push-4', workoutTemplateId: 'push-a', exerciseId: 'exe-cable-fly', displayName: '绳索夹胸', orderIndex: 4,
    targetSets: 3, minReps: 10, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  { id: 'wte-push-5', workoutTemplateId: 'push-a', exerciseId: 'exe-lateral-raise', displayName: '哑铃侧平举', orderIndex: 5,
    targetSets: 3, minReps: 10, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  { id: 'wte-push-6', workoutTemplateId: 'push-a', exerciseId: 'exe-cable-pushdown', displayName: '绳索下压', orderIndex: 6,
    targetSets: 3, minReps: 10, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  // ===== 拉日A =====
  { id: 'wte-pull-1', workoutTemplateId: 'pull-a', exerciseId: 'exe-pulldown', displayName: '引体向上/高位下拉', orderIndex: 1,
    targetSets: 4, minReps: 8, maxReps: 12, restSecondsMin: 90, restSecondsMax: 120, warmupSets: 2, warmupPercent: 50, isEachSide: false },
  { id: 'wte-pull-2', workoutTemplateId: 'pull-a', exerciseId: 'exe-bent-row', displayName: '杠铃俯身划船', orderIndex: 2,
    targetSets: 4, minReps: 8, maxReps: 12, restSecondsMin: 90, restSecondsMax: 120, warmupSets: 2, warmupPercent: 50, isEachSide: false },
  { id: 'wte-pull-3', workoutTemplateId: 'pull-a', exerciseId: 'exe-seated-cable-row', displayName: '坐姿绳索划船', orderIndex: 3,
    targetSets: 3, minReps: 8, maxReps: 12, restSecondsMin: 90, restSecondsMax: 90, warmupSets: 1, warmupPercent: 50, isEachSide: false },
  { id: 'wte-pull-4', workoutTemplateId: 'pull-a', exerciseId: 'exe-straight-arm-pulldown', displayName: '直臂绳索下压', orderIndex: 4,
    targetSets: 3, minReps: 10, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  { id: 'wte-pull-5', workoutTemplateId: 'pull-a', exerciseId: 'exe-face-pull', displayName: '面拉', orderIndex: 5,
    targetSets: 3, minReps: 10, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  { id: 'wte-pull-6', workoutTemplateId: 'pull-a', exerciseId: 'exe-bb-curl', displayName: '杠铃弯举', orderIndex: 6,
    targetSets: 3, minReps: 8, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  { id: 'wte-pull-7', workoutTemplateId: 'pull-a', exerciseId: 'exe-alt-db-curl', displayName: '哑铃交替弯举', orderIndex: 7,
    targetSets: 2, minReps: 10, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  // ===== 腿日 =====
  { id: 'wte-legs-1', workoutTemplateId: 'legs', exerciseId: 'exe-squat', displayName: '杠铃深蹲', orderIndex: 1,
    targetSets: 4, minReps: 8, maxReps: 12, restSecondsMin: 120, restSecondsMax: 150, warmupSets: 2, warmupPercent: 50, isEachSide: false },
  { id: 'wte-legs-2', workoutTemplateId: 'legs', exerciseId: 'exe-romanian-deadlift', displayName: '罗马尼亚硬拉', orderIndex: 2,
    targetSets: 4, minReps: 8, maxReps: 12, restSecondsMin: 120, restSecondsMax: 120, warmupSets: 2, warmupPercent: 50, isEachSide: false },
  { id: 'wte-legs-3', workoutTemplateId: 'legs', exerciseId: 'exe-leg-press', displayName: '腿举', orderIndex: 3,
    targetSets: 3, minReps: 10, maxReps: 12, restSecondsMin: 90, restSecondsMax: 90, warmupSets: 1, warmupPercent: 50, isEachSide: false },
  { id: 'wte-legs-4', workoutTemplateId: 'legs', exerciseId: 'exe-leg-ext', displayName: '坐姿腿屈伸', orderIndex: 4,
    targetSets: 3, minReps: 10, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  { id: 'wte-legs-5', workoutTemplateId: 'legs', exerciseId: 'exe-leg-curl', displayName: '俯卧腿弯举', orderIndex: 5,
    targetSets: 3, minReps: 10, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  { id: 'wte-legs-6', workoutTemplateId: 'legs', exerciseId: 'exe-standing-calf', displayName: '站姿提踵', orderIndex: 6,
    targetSets: 4, minReps: 12, maxReps: 15, restSecondsMin: 45, restSecondsMax: 45, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  // ===== 综合复合日 =====
  { id: 'wte-comp-1', workoutTemplateId: 'compound', exerciseId: 'exe-db-bench', displayName: '哑铃卧推', orderIndex: 1,
    targetSets: 3, minReps: 10, maxReps: 10, restSecondsMin: 90, restSecondsMax: 90, warmupSets: 1, warmupPercent: 50, isEachSide: false },
  { id: 'wte-comp-2', workoutTemplateId: 'compound', exerciseId: 'exe-db-row', displayName: '单臂哑铃划船', orderIndex: 2,
    targetSets: 3, minReps: 10, maxReps: 10, restSecondsMin: 90, restSecondsMax: 90, warmupSets: 1, warmupPercent: 50, isEachSide: true },
  { id: 'wte-comp-3', workoutTemplateId: 'compound', exerciseId: 'exe-smith-lunge', displayName: '史密斯机箭步蹲', orderIndex: 3,
    targetSets: 3, minReps: 10, maxReps: 10, restSecondsMin: 90, restSecondsMax: 90, warmupSets: 1, warmupPercent: 50, isEachSide: true },
  { id: 'wte-comp-4', workoutTemplateId: 'compound', exerciseId: 'exe-db-ohp', displayName: '哑铃推举', orderIndex: 4,
    targetSets: 3, minReps: 10, maxReps: 10, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 1, warmupPercent: 50, isEachSide: false },
  { id: 'wte-comp-5', workoutTemplateId: 'compound', exerciseId: 'exe-hammer-curl', displayName: '锤式弯举', orderIndex: 5,
    targetSets: 2, minReps: 12, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
  { id: 'wte-comp-6', workoutTemplateId: 'compound', exerciseId: 'exe-overhead-ext', displayName: '颈后臂屈伸', orderIndex: 6,
    targetSets: 2, minReps: 12, maxReps: 12, restSecondsMin: 60, restSecondsMax: 60, warmupSets: 0, warmupPercent: 0, isEachSide: false },
]
